apiVersion: v1
kind: Secret
metadata:
  name: firebase-credentials
  namespace: kaleidoplan
type: Opaque
data:
  api-key: ${FIREBASE_API_KEY_BASE64}
  auth-domain: ${FIREBASE_AUTH_DOMAIN_BASE64}
  project-id: ${FIREBASE_PROJECT_ID_BASE64}
  storage-bucket: ${FIREBASE_STORAGE_BUCKET_BASE64}
  messaging-sender-id: ${FIREBASE_MESSAGING_SENDER_ID_BASE64}
  app-id: ${FIREBASE_APP_ID_BASE64}
  measurement-id: ${FIREBASE_MEASUREMENT_ID_BASE64}
