name: Bundle Size Analysis

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - "yarn.lock"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate build stats
        run: npm run build -- --stats

      - name: Analyze bundle size
        uses: jackyef/bundlewatch-gh-action@master
        with:
          build-script: npm run build
          bundlewatch-github-token: ${{ secrets.GITHUB_TOKEN }}
