name: Kaleidoplan CI/CD

on:
  push:
    branches: [master, develop]
    paths-ignore:
      - "**.md" # Only ignore markdown files
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  checks: write
  pull-requests: write

jobs:
  # Commenting out the labeler job as requested
  # label:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/labeler@v5
  #       with:
  #         repo-token: ${{ secrets.PAT_TOKEN }}

  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Adding the conditional HTML linting from GitLab CI
      - name: Check for HTML files and lint if found
        run: |
          if [ "$(find . -path './node_modules' -prune -o -type f -name '*.html' -print)" ]; then 
            npm run lint-html
          fi

      - name: Lint code
        run: npm run lint

      - name: Check formatting
        run: npx prettier --check "**/*.{js,jsx,ts,tsx,json,md,css,scss,html}"

      - name: Check TypeScript types
        run: npm run typecheck

      - name: Run unit tests
        run: npm test -- --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build
          retention-days: 7

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "npm"
          cache-dependency-path: "./server/package-lock.json"

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Check TypeScript types
        working-directory: ./server
        run: npm run typecheck

      - name: Lint code
        working-directory: ./server
        run: npm run lint

      - name: Run tests
        working-directory: ./server
        run: npm test

  lighthouse:
    name: Lighthouse Web Vitals
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: build

      - name: Run Lighthouse CI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
